### PR TITLE
Add feature to generate the file url

### PR DESCRIPTION
**Pull request by giuseppeg**
This should allow to use the plugin with sublime too (my editor of choice)

### CODE REVIEW

**Comment by siddharthkp** [comment]
PR welcome if you'd like to tackle it :)

The way I would approach it would be add a [plugin option](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#plugin-options) and include an additional file based on that called `set-editor.js` or something which sets the editor as global variable which can be read by `script.js`

**Comment by giuseppeg** [comment]
> Thanks for the PR!
> 
> The way I would approach it would be add a [plugin option](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#plugin-options) and [import an additional file](https://github.com/siddharthkp/babel-plugin-open-source/blob/main/packages/babel-plugin-open-source/babel.js#L21-L24) based on that called `set-editor-sublime.js`, `set-editor-atom.js` which sets the editor as global variable which can be read by `script.js`

I figured I'd leave it to the user to implement other editors integrations so that you don't have to bother but if you want I can do the option thing.

**Comment by siddharthkp** [comment]
> I figured I'd leave it to the user to implement other editors integrations

umm, not a fan of leaking details. I don't mind the editor approach because there are only a few popular editors

**Comment by siddharthkp** [comment]
Solved in https://github.com/siddharthkp/babel-plugin-open-source/pull/11 :)

**Comment by giuseppeg** [comment]
oh sweet thank you!

**Pull request closed without merging**
